# Generated by Django 2.0 on 2019-12-30 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0001_initial'),
        ('df_goods', '0002_auto_20191227_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.Goodsinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.Userinfo')),
            ],
            options={
                'db_table': 'cartinfo',
            },
        ),
    ]
